
name: Jogo da Memória - Pipeline

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  verificar-projeto:

    runs-on: ubuntu-latest

    steps:

      - name: 📥 Baixar o projeto
        uses: actions/checkout@v4

      - name: 🔎 Verificar arquivos
        run: |
          echo "Verificando o projeto..."

          test -f index.html

          echo "✅ index.html encontrado!"
          echo "🎉 Projeto verificado com sucesso!"

